#!/bin/bash

###############################################################
#          jupyter/jupyterlab extensions/kernels              #
###############################################################

# ipython-sql extension install
echo "Ipython-sql extension install"
jupyter serverextension enable jupyterlab_sql --py --sys-prefix

###############################################################
#             moving to a local installation folder           #
###############################################################

mkdir ~/resources/local
cd    ~/resources/local

###############################################################
#             mysql minimal installation commands             #
###############################################################

export MYSQL_VERSION=8.0.17
echo "export MYSQL_VERSION=${MYSQL_VERSION}" >> ~/.bashrc
echo "export MYSQL_VERSION=${MYSQL_VERSION}" >> ~/.profile

export MYSQL_HOME=$(pwd)/mysql-${MYSQL_VERSION}
echo "export MYSQL_HOME=${MYSQL_HOME}"       >> ~/.bashrc
echo "export MYSQL_HOME=${MYSQL_HOME}"       >> ~/.profile

       
wget https://cdn.mysql.com/archives/mysql-8.0/mysql-${MYSQL_VERSION}-linux-x86_64-minimal.tar.xz -q  && \
tar -xf mysql-${MYSQL_VERSION}-linux-x86_64-minimal.tar.xz >> /dev/null                              && \
rm      mysql-${MYSQL_VERSION}-linux-x86_64-minimal.tar.xz                                           && \
mv      mysql-${MYSQL_VERSION}-linux-x86_64-minimal        mysql-${MYSQL_VERSION} 

# adding bin/ to $path
echo "export PATH=\$PATH:\$MYSQL_HOME/bin"   >> ~/.bashrc
echo "export PATH=\$PATH:\$MYSQL_HOME/bin"   >> ~/.profile

mysql -h localhost -u root -p